Merged PR 21734: DEV: equalize org.gradle.jvmargs properties for indigo and example app
DEV: equalize org.gradle.jvmargs properties for indigo and example app

This will help to reuse gradle daemons on CI. Also Builds often fail with out of memory now and it needs an increase for MaxMetaspaceSize.

Gradle daemons launched with different `jvmargs` are not compatible, then you see following in CI logs:
```
Starting a Gradle Daemon, 2 incompatible and 4 stopped Daemons could not be reused, use --status for details
```

Second issue, IndiGO Docs pipeline fails with:
```
> Task :examples_media_custompolicies:mergeExtDexDebug
ERROR:D8: java.lang.OutOfMemoryError: Java heap space
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
```
Because now it needs more memory, we build 5+ apks instead of one.